import type { SupportedLanguage } from "./i18n";

const es = {
  missing: "Falta un paso", emailRequired: "Escribe tu correo.", credentialsRequired: "Escribe tu correo y contraseña.",
  agreementTitle: "Revisa el acuerdo", agreementBody: "Confirma que leíste el aviso de privacidad y las reglas de comunidad.",
  passwordTitle: "Revisa tu contraseña", passwordMismatch: "La confirmación debe coincidir exactamente con la contraseña.",
  unavailable: "Verificación no disponible", checkEmail: "Revisa tu correo", resetSent: "Si existe una cuenta con ese correo, recibirás un enlace seguro. Ábrelo en este dispositivo para volver a Clean4Jesus y cambiar la contraseña.",
  failed: "No pudimos continuar", retry: "Intenta nuevamente.", confirmAccount: "Confirma tu cuenta", sentLink: "Enviamos el enlace de confirmación a:",
  openSameDevice: "Abre el enlace desde este mismo dispositivo para regresar a Clean4Jesus y completar el acceso.", spamHelp: "Si no lo encuentras, revisa spam o correo no deseado antes de solicitar otro.",
  resending: "Reenviando...", resend: "Reenviar correo", resent: "Correo reenviado. Usa el enlace más reciente que recibas.", resendError: "No pudimos reenviarlo. Revisa tu conexión e intenta nuevamente.",
  anotherEmail: "Usar otro correo", pending: "Puedes cerrar esta pantalla mientras llega el mensaje. Tu cuenta quedará pendiente hasta que abras el enlace.",
  protected: "Comunidad protegida", signInTitle: "Vuelve a caminar acompañado", signUpTitle: "Crea tu espacio seguro", forgotTitle: "Recupera tu acceso",
  cardBody: "Tu cuenta permite conservar testimonios, pedidos de oración y respuestas. Tu correo nunca se muestra en el feed.",
  signIn: "Ingresar", signUp: "Crear cuenta", connecting: "Conectando...", google: "Continuar con Google", googleConsent: "Al continuar aceptas el aviso de privacidad y las reglas de comunidad. Google solo se usa para verificar tu identidad.",
  orEmail: "o usa tu correo", displayName: "Nombre visible", displayNamePlaceholder: "Cómo quieres que te llamemos", email: "Correo", password: "Contraseña", passwordHint: "Mínimo 10 caracteres",
  confirmPassword: "Confirmar contraseña", repeatPassword: "Repite tu contraseña", accept: "Confirmo que tengo 18 años o más y acepto la Política de Privacidad, los Términos y las Reglas de Comunidad.",
  enter: "Entrar a comunidad", create: "Crear mi cuenta", sendLink: "Enviar enlace seguro", forgot: "Olvidé mi contraseña", backSignIn: "Volver a ingresar",
  privacy: "La sesión se conserva de forma privada en este dispositivo y puedes cerrarla desde Ajustes.",
  callbackVerifying: "Verificando tu acceso", callbackBody: "Protegemos tu sesión mientras vuelves a Clean4Jesus.", linkUnavailable: "Enlace no disponible", backCommunity: "Volver a Comunidad",
} as const;

type AuthCopy = { [Key in keyof typeof es]: string };

const en: AuthCopy = {
  missing: "One step is missing", emailRequired: "Enter your email.", credentialsRequired: "Enter your email and password.", agreementTitle: "Review the agreement", agreementBody: "Confirm that you read the privacy notice and community guidelines.", passwordTitle: "Check your password", passwordMismatch: "The confirmation must exactly match the password.", unavailable: "Verification unavailable", checkEmail: "Check your email", resetSent: "If an account exists for that email, you will receive a secure link. Open it on this device to return to Clean4Jesus and change your password.", failed: "We could not continue", retry: "Try again.", confirmAccount: "Confirm your account", sentLink: "We sent the confirmation link to:", openSameDevice: "Open the link on this same device to return to Clean4Jesus and complete access.", spamHelp: "If you cannot find it, check spam or junk before requesting another one.", resending: "Resending...", resend: "Resend email", resent: "Email resent. Use the newest link you receive.", resendError: "We could not resend it. Check your connection and try again.", anotherEmail: "Use another email", pending: "You can close this screen while the message arrives. Your account remains pending until you open the link.", protected: "Protected community", signInTitle: "Walk with support again", signUpTitle: "Create your safe space", forgotTitle: "Recover your access", cardBody: "Your account keeps your testimonies, prayer requests, and replies. Your email is never shown in the feed.", signIn: "Sign in", signUp: "Create account", connecting: "Connecting...", google: "Continue with Google", googleConsent: "By continuing, you accept the privacy notice and community guidelines. Google is used only to verify your identity.", orEmail: "or use your email", displayName: "Display name", displayNamePlaceholder: "How should we call you?", email: "Email", password: "Password", passwordHint: "At least 10 characters", confirmPassword: "Confirm password", repeatPassword: "Repeat your password", accept: "I confirm that I am 18 or older and accept the Privacy Policy, Terms, and Community Guidelines.", enter: "Enter community", create: "Create my account", sendLink: "Send secure link", forgot: "Forgot my password", backSignIn: "Back to sign in", privacy: "Your session is stored privately on this device and you can sign out from Settings.", callbackVerifying: "Verifying your access", callbackBody: "We are protecting your session while you return to Clean4Jesus.", linkUnavailable: "Link unavailable", backCommunity: "Back to Community",
};

const fr: AuthCopy = {
  missing: "Une étape manque", emailRequired: "Saisissez votre e-mail.", credentialsRequired: "Saisissez votre e-mail et votre mot de passe.", agreementTitle: "Vérifiez l'accord", agreementBody: "Confirmez avoir lu l'avis de confidentialité et les règles de la communauté.", passwordTitle: "Vérifiez votre mot de passe", passwordMismatch: "La confirmation doit correspondre exactement au mot de passe.", unavailable: "Vérification indisponible", checkEmail: "Consultez votre e-mail", resetSent: "Si un compte correspond à cet e-mail, vous recevrez un lien sécurisé. Ouvrez-le sur cet appareil pour revenir à Clean4Jesus et modifier votre mot de passe.", failed: "Impossible de continuer", retry: "Réessayez.", confirmAccount: "Confirmez votre compte", sentLink: "Nous avons envoyé le lien de confirmation à :", openSameDevice: "Ouvrez le lien sur ce même appareil pour revenir à Clean4Jesus et terminer l'accès.", spamHelp: "Si vous ne le trouvez pas, vérifiez les courriers indésirables avant d'en demander un autre.", resending: "Renvoi...", resend: "Renvoyer l'e-mail", resent: "E-mail renvoyé. Utilisez le lien le plus récent.", resendError: "Impossible de le renvoyer. Vérifiez votre connexion et réessayez.", anotherEmail: "Utiliser un autre e-mail", pending: "Vous pouvez fermer cet écran pendant l'arrivée du message. Le compte restera en attente jusqu'à l'ouverture du lien.", protected: "Communauté protégée", signInTitle: "Marchez de nouveau accompagné", signUpTitle: "Créez votre espace sûr", forgotTitle: "Récupérez votre accès", cardBody: "Votre compte conserve vos témoignages, demandes de prière et réponses. Votre e-mail n'apparaît jamais dans le fil.", signIn: "Se connecter", signUp: "Créer un compte", connecting: "Connexion...", google: "Continuer avec Google", googleConsent: "En continuant, vous acceptez l'avis de confidentialité et les règles de la communauté. Google sert uniquement à vérifier votre identité.", orEmail: "ou utilisez votre e-mail", displayName: "Nom visible", displayNamePlaceholder: "Comment souhaitez-vous être appelé ?", email: "E-mail", password: "Mot de passe", passwordHint: "Au moins 10 caractères", confirmPassword: "Confirmer le mot de passe", repeatPassword: "Répétez votre mot de passe", accept: "Je confirme avoir 18 ans ou plus et j'accepte la Politique de confidentialité, les Conditions et les Règles de la communauté.", enter: "Entrer dans la communauté", create: "Créer mon compte", sendLink: "Envoyer le lien sécurisé", forgot: "Mot de passe oublié", backSignIn: "Retour à la connexion", privacy: "Votre session est conservée de façon privée sur cet appareil et vous pouvez vous déconnecter depuis les Réglages.", callbackVerifying: "Vérification de votre accès", callbackBody: "Nous protégeons votre session pendant votre retour vers Clean4Jesus.", linkUnavailable: "Lien indisponible", backCommunity: "Retour à la Communauté",
};

const pt: AuthCopy = {
  missing: "Falta uma etapa", emailRequired: "Digite seu e-mail.", credentialsRequired: "Digite seu e-mail e sua senha.", agreementTitle: "Revise o acordo", agreementBody: "Confirme que leu o aviso de privacidade e as regras da comunidade.", passwordTitle: "Confira sua senha", passwordMismatch: "A confirmação deve ser exatamente igual à senha.", unavailable: "Verificação indisponível", checkEmail: "Confira seu e-mail", resetSent: "Se existir uma conta com esse e-mail, você receberá um link seguro. Abra-o neste dispositivo para voltar ao Clean4Jesus e alterar a senha.", failed: "Não foi possível continuar", retry: "Tente novamente.", confirmAccount: "Confirme sua conta", sentLink: "Enviamos o link de confirmação para:", openSameDevice: "Abra o link neste mesmo dispositivo para voltar ao Clean4Jesus e concluir o acesso.", spamHelp: "Se não encontrar, verifique spam ou lixo eletrônico antes de pedir outro.", resending: "Reenviando...", resend: "Reenviar e-mail", resent: "E-mail reenviado. Use o link mais recente recebido.", resendError: "Não foi possível reenviar. Verifique sua conexão e tente novamente.", anotherEmail: "Usar outro e-mail", pending: "Você pode fechar esta tela enquanto a mensagem chega. Sua conta ficará pendente até abrir o link.", protected: "Comunidade protegida", signInTitle: "Volte a caminhar acompanhado", signUpTitle: "Crie seu espaço seguro", forgotTitle: "Recupere seu acesso", cardBody: "Sua conta mantém testemunhos, pedidos de oração e respostas. Seu e-mail nunca aparece no feed.", signIn: "Entrar", signUp: "Criar conta", connecting: "Conectando...", google: "Continuar com Google", googleConsent: "Ao continuar, você aceita o aviso de privacidade e as regras da comunidade. O Google é usado somente para verificar sua identidade.", orEmail: "ou use seu e-mail", displayName: "Nome visível", displayNamePlaceholder: "Como você quer ser chamado?", email: "E-mail", password: "Senha", passwordHint: "No mínimo 10 caracteres", confirmPassword: "Confirmar senha", repeatPassword: "Repita sua senha", accept: "Confirmo que tenho 18 anos ou mais e aceito a Política de Privacidade, os Termos e as Regras da Comunidade.", enter: "Entrar na comunidade", create: "Criar minha conta", sendLink: "Enviar link seguro", forgot: "Esqueci minha senha", backSignIn: "Voltar para entrar", privacy: "Sua sessão fica armazenada de forma privada neste dispositivo e você pode sair em Configurações.", callbackVerifying: "Verificando seu acesso", callbackBody: "Protegemos sua sessão enquanto você volta ao Clean4Jesus.", linkUnavailable: "Link indisponível", backCommunity: "Voltar à Comunidade",
};

const tables: Record<SupportedLanguage, AuthCopy> = { es, en, fr, pt };
export function getAuthText(language: SupportedLanguage) { return tables[language]; }
