import type { SupportedLanguage } from "./i18n";

const copy = {
  es: { title: "Informe de preparación iOS", subtitle: "Estado de paridad y preparación técnica para la versión de iOS.", shared: "Capas listas (compartidas)", native: "Capa nativa iOS (Screen Time)", items: ["Autenticación (Supabase + Google OAuth PKCE)", "Palabra (devocionales y planes con caché offline)", "Comunidad (testimonios, oraciones y moderación)", "Internacionalización (ES, EN, FR, PT-BR)", "Temas (modo claro y modo oscuro)"], nativeItems: ["Contratos TypeScript y adaptadores", "Módulo Swift nativo", "Extensiones nativas de Screen Time", "App Group compartido", "Interrupción visual nativa y rescate guiado"], back: "Volver" },
  en: { title: "iOS readiness report", subtitle: "Parity and technical readiness for the iOS version.", shared: "Shared layers ready", native: "iOS native layer (Screen Time)", items: ["Authentication (Supabase + Google OAuth PKCE)", "Word (devotionals and offline plan cache)", "Community (testimonies, prayers, and moderation)", "Localization (ES, EN, FR, PT-BR)", "Themes (light and dark mode)"], nativeItems: ["TypeScript contracts and adapters", "Native Swift module", "Screen Time native extensions", "Shared App Group", "Native visual interruption and guided rescue"], back: "Back" },
  fr: { title: "Rapport de préparation iOS", subtitle: "État de parité et de préparation technique pour iOS.", shared: "Couches partagées prêtes", native: "Couche native iOS (Screen Time)", items: ["Authentification (Supabase + Google OAuth PKCE)", "Parole (dévotionnels et plans hors ligne)", "Communauté (témoignages, prières et modération)", "Internationalisation (ES, EN, FR, PT-BR)", "Thèmes (clair et sombre)"], nativeItems: ["Contrats TypeScript et adaptateurs", "Module Swift natif", "Extensions natives Screen Time", "App Group partagé", "Interruption visuelle native et secours guidé"], back: "Retour" },
  pt: { title: "Relatório de preparação do iOS", subtitle: "Estado de paridade e preparação técnica para iOS.", shared: "Camadas compartilhadas prontas", native: "Camada nativa do iOS (Screen Time)", items: ["Autenticação (Supabase + Google OAuth PKCE)", "Palavra (devocionais e planos offline)", "Comunidade (testemunhos, orações e moderação)", "Internacionalização (ES, EN, FR, PT-BR)", "Temas (claro e escuro)"], nativeItems: ["Contratos TypeScript e adaptadores", "Módulo Swift nativo", "Extensões nativas do Screen Time", "App Group compartilhado", "Interrupção visual nativa e resgate guiado"], back: "Voltar" },
} as const;

export function getIosReadinessText(language: SupportedLanguage) {
  return copy[language];
}
