import type { SupportedLanguage } from "./i18n";

const es = {
  gateDaily: "Refugio diario", gateActive: "Refugio activo", gateOff: "Refugio apagado", gateReadyTitle: "La protección ya está encendida", gateSetupTitle: "Primero configuramos tu refugio", gateBody: "Empieza con una persona de confianza y la VPN local. La Accesibilidad es opcional para interrupciones visibles y no se activa por defecto.", ready: "Listo", create: "Falta configurar", active: "Activa", pending: "Pendiente", steps: "Paso a paso", stepPin: "1. Elige el correo de tu persona de confianza; ella recibirá el PIN.", stepVpn: "2. Acepta la VPN local de Clean4Jesus para activar la protección base.", stepAccessibility: "Capa opcional: activa Accesibilidad solo si quieres interrupciones sobre contenido visible.", gatePaused: "Refugio en pausa", gatePausedBody: "Activa la VPN local para completar la protección base.", vpn: "VPN local", accessibility: "Accesibilidad opcional", gateConfirm: "Ya lo activé", gateEnter: "Entrar a Clean4Jesus", gatePrepare: "Preparar refugio", openAccessibility: "Configurar Accesibilidad opcional", setupPending: "Configuración pendiente", setupPendingBody: "Android aún no confirma el PIN y la VPN local. Activa las capas pendientes antes de continuar.",
  runtimeBadge: "Compatibilidad", runtimePending: "Revisión pendiente", runtimeRequired: "Actualización requerida", runtimeChecking: "Estamos revisando tu versión", runtimeCheckingBody: "Queremos asegurarnos de que uses una app compatible con la protección y la comunidad actuales.", runtimeFailed: "No pudimos validar tu versión", yourVersion: "Tu versión", minimum: "Mínima", retry: "Volver a comprobar", update: "Actualizar ahora", understood: "Entendido", updateHelp: "Instala la APK más reciente que te compartamos para continuar.",
  interruptionMessage: "MENSAJE O VERSÍCULO", interruptionReference: "REFERENCIA O FIRMA", referenceA11y: "Referencia o firma", changeImage: "Cambiar imagen", chooseImage: "Elegir imagen de la galería", removeImage: "Quitar imagen",
  passwordTitle: "Tu contraseña debe cuidarte bien", passwordMin: "Al menos 10 caracteres", passwordLetter: "Incluye al menos una letra", passwordNumber: "Incluye al menos un número", passwordEmail: "Evita usar tu correo dentro de la contraseña", passwordName: "Evita usar tu nombre visible dentro de la contraseña",
} as const;

type Copy = { [K in keyof typeof es]: string };
const en: Copy = {
  gateDaily: "Daily refuge", gateActive: "Refuge active", gateOff: "Refuge off", gateReadyTitle: "Protection is already on", gateSetupTitle: "First, set up protection", gateBody: "Everything starts here: PIN, local VPN, and Accessibility. System private DNS stays unchanged so mobile data and YouTube keep working.", ready: "Ready", create: "Create it", active: "Active", pending: "Pending", steps: "Step by step", stepPin: "1. Create or confirm your 4-digit PIN.", stepVpn: "2. Accept the Clean4Jesus local VPN to enable base protection.", stepAccessibility: "3. Enable Clean4Jesus in Accessibility to show the interruption screen.", gatePaused: "Refuge paused", gatePausedBody: "Enable the local VPN and Accessibility. Private DNS remains an advanced option in Settings.", vpn: "Local VPN", accessibility: "Accessibility", gateConfirm: "I enabled it", gateEnter: "Enter Clean4Jesus", gatePrepare: "Prepare refuge", openAccessibility: "Open Accessibility", setupPending: "Setup incomplete", setupPendingBody: "Android has not confirmed the PIN, local VPN, and Accessibility yet. Enable the missing layers before continuing.",
  runtimeBadge: "Compatibility", runtimePending: "Review pending", runtimeRequired: "Update required", runtimeChecking: "Checking your version", runtimeCheckingBody: "We are making sure your app is compatible with the current protection and community.", runtimeFailed: "We could not validate your version", yourVersion: "Your version", minimum: "Minimum", retry: "Check again", update: "Update now", understood: "Got it", updateHelp: "Install the latest APK shared with you to continue.",
  interruptionMessage: "MESSAGE OR VERSE", interruptionReference: "REFERENCE OR SIGNATURE", referenceA11y: "Reference or signature", changeImage: "Change image", chooseImage: "Choose image from gallery", removeImage: "Remove image",
  passwordTitle: "Your password should protect you well", passwordMin: "At least 10 characters", passwordLetter: "Include at least one letter", passwordNumber: "Include at least one number", passwordEmail: "Do not include your email in the password", passwordName: "Do not include your display name in the password",
};
const fr: Copy = {
  gateDaily: "Refuge quotidien", gateActive: "Refuge actif", gateOff: "Refuge désactivé", gateReadyTitle: "La protection est déjà active", gateSetupTitle: "Configurons d'abord la protection", gateBody: "Tout commence ici : PIN, VPN local et Accessibilité. Le DNS privé du système reste inchangé afin de préserver les données mobiles et YouTube.", ready: "Prêt", create: "À créer", active: "Active", pending: "En attente", steps: "Pas à pas", stepPin: "1. Créez ou confirmez votre PIN à 4 chiffres.", stepVpn: "2. Acceptez le VPN local Clean4Jesus pour activer la protection de base.", stepAccessibility: "3. Activez Clean4Jesus dans Accessibilité pour afficher l'écran d'interruption.", gatePaused: "Refuge en pause", gatePausedBody: "Activez le VPN local et Accessibilité. Le DNS privé reste une option avancée dans les Réglages.", vpn: "VPN local", accessibility: "Accessibilité", gateConfirm: "Je l'ai activé", gateEnter: "Entrer dans Clean4Jesus", gatePrepare: "Préparer le refuge", openAccessibility: "Ouvrir Accessibilité", setupPending: "Configuration incomplète", setupPendingBody: "Android n'a pas encore confirmé le PIN, le VPN local et Accessibilité. Activez les couches manquantes avant de continuer.",
  runtimeBadge: "Compatibilité", runtimePending: "Vérification en attente", runtimeRequired: "Mise à jour requise", runtimeChecking: "Vérification de votre version", runtimeCheckingBody: "Nous vérifions que votre application est compatible avec la protection et la communauté actuelles.", runtimeFailed: "Impossible de valider votre version", yourVersion: "Votre version", minimum: "Minimum", retry: "Vérifier à nouveau", update: "Mettre à jour", understood: "Compris", updateHelp: "Installez le dernier APK qui vous a été partagé pour continuer.",
  interruptionMessage: "MESSAGE OU VERSET", interruptionReference: "RÉFÉRENCE OU SIGNATURE", referenceA11y: "Référence ou signature", changeImage: "Changer l'image", chooseImage: "Choisir une image de la galerie", removeImage: "Retirer l'image",
  passwordTitle: "Votre mot de passe doit bien vous protéger", passwordMin: "Au moins 10 caractères", passwordLetter: "Inclure au moins une lettre", passwordNumber: "Inclure au moins un chiffre", passwordEmail: "N'utilisez pas votre e-mail dans le mot de passe", passwordName: "N'utilisez pas votre nom public dans le mot de passe",
};
const pt: Copy = {
  gateDaily: "Refúgio diário", gateActive: "Refúgio ativo", gateOff: "Refúgio desligado", gateReadyTitle: "A proteção já está ativa", gateSetupTitle: "Primeiro configuramos a proteção", gateBody: "Tudo começa aqui: PIN, VPN local e Acessibilidade. O DNS privado do sistema não é alterado para preservar os dados móveis e o YouTube.", ready: "Pronto", create: "Falta criar", active: "Ativa", pending: "Pendente", steps: "Passo a passo", stepPin: "1. Crie ou confirme seu PIN de 4 dígitos.", stepVpn: "2. Aceite a VPN local do Clean4Jesus para ativar a proteção base.", stepAccessibility: "3. Ative o Clean4Jesus em Acessibilidade para mostrar a tela de interrupção.", gatePaused: "Refúgio em pausa", gatePausedBody: "Ative a VPN local e a Acessibilidade. O DNS privado fica como opção avançada em Configurações.", vpn: "VPN local", accessibility: "Acessibilidade", gateConfirm: "Já ativei", gateEnter: "Entrar no Clean4Jesus", gatePrepare: "Preparar refúgio", openAccessibility: "Abrir Acessibilidade", setupPending: "Configuração pendente", setupPendingBody: "O Android ainda não confirmou o PIN, a VPN local e a Acessibilidade. Ative as camadas pendentes antes de continuar.",
  runtimeBadge: "Compatibilidade", runtimePending: "Revisão pendente", runtimeRequired: "Atualização necessária", runtimeChecking: "Verificando sua versão", runtimeCheckingBody: "Estamos confirmando que seu aplicativo é compatível com a proteção e a comunidade atuais.", runtimeFailed: "Não foi possível validar sua versão", yourVersion: "Sua versão", minimum: "Mínima", retry: "Verificar novamente", update: "Atualizar agora", understood: "Entendi", updateHelp: "Instale o APK mais recente compartilhado com você para continuar.",
  interruptionMessage: "MENSAGEM OU VERSÍCULO", interruptionReference: "REFERÊNCIA OU ASSINATURA", referenceA11y: "Referência ou assinatura", changeImage: "Trocar imagem", chooseImage: "Escolher imagem da galeria", removeImage: "Remover imagem",
  passwordTitle: "Sua senha deve proteger você bem", passwordMin: "No mínimo 10 caracteres", passwordLetter: "Inclua pelo menos uma letra", passwordNumber: "Inclua pelo menos um número", passwordEmail: "Evite usar seu e-mail na senha", passwordName: "Evite usar seu nome visível na senha",
};

const tables: Record<SupportedLanguage, Copy> = { es, en, fr, pt };
const optionalAccessibilityCopy: Partial<Record<SupportedLanguage, Partial<Copy>>> = {
  en: { accessibility: "Optional accessibility", gateBody: "Start with a trusted person and the local VPN. Accessibility is optional for visible interruptions and is never enabled by default.", gatePausedBody: "Enable the local VPN to complete base protection.", openAccessibility: "Configure optional accessibility", setupPendingBody: "Android has not confirmed the PIN and local VPN yet. Enable the missing layers to continue.", stepAccessibility: "Optional layer: enable Accessibility only if you want visible content interruptions.", stepPin: "1. Choose your trusted person’s email; they will receive the PIN." },
  fr: { accessibility: "Accessibilité facultative", gateBody: "Commencez avec une personne de confiance et le VPN local. L’Accessibilité reste facultative pour les interruptions visibles et n’est jamais activée par défaut.", gatePausedBody: "Activez le VPN local pour compléter la protection de base.", openAccessibility: "Configurer l’Accessibilité facultative", setupPendingBody: "Android n’a pas encore confirmé le PIN et le VPN local. Activez les couches manquantes pour continuer.", stepAccessibility: "Couche facultative : activez l’Accessibilité uniquement pour les interruptions visibles.", stepPin: "1. Choisissez l’adresse de votre personne de confiance ; elle recevra le PIN." },
  pt: { accessibility: "Acessibilidade opcional", gateBody: "Comece com uma pessoa de confiança e a VPN local. A Acessibilidade é opcional para interrupções visíveis e nunca é ativada por padrão.", gatePausedBody: "Ative a VPN local para concluir a proteção base.", openAccessibility: "Configurar Acessibilidade opcional", setupPendingBody: "O Android ainda não confirmou o PIN e a VPN local. Ative as camadas pendentes para continuar.", stepAccessibility: "Camada opcional: ative a Acessibilidade somente se quiser interrupções visíveis.", stepPin: "1. Escolha o e-mail da sua pessoa de confiança; ela receberá o PIN." },
};
export const getSecondaryText = (language: SupportedLanguage): Copy => ({ ...tables[language], ...optionalAccessibilityCopy[language] });
