import type { SupportedLanguage } from "@/features/i18n/i18n";

const copy = {
  es: {
    eyebrow: "CENTRO LEGAL",
    accept: "Confirmo que tengo 18 años o más y acepto el Aviso de privacidad, los Términos de uso y las Reglas de comunidad.",
    acceptAction: "Aceptar y entrar",
    accountDeletion: "Eliminar una cuenta",
    accountDeletionHint: "Solicitud web y explicación del proceso",
    checkError: "No pudimos verificar tu aceptación. Revisa tu conexión e inténtalo nuevamente.",
    guidelines: "Reglas de comunidad",
    guidelinesHint: "Convivencia, reportes y moderación",
    intro: "Consulta las reglas vigentes y cómo protegemos tus datos.",
    privacy: "Aviso de privacidad",
    privacyHint: "Datos locales, datos en la nube y tus derechos",
    reconsentBody: "Actualizamos la base legal de Comunidad. Para continuar, revisa y acepta la versión vigente.",
    reconsentTitle: "Cuidamos este espacio con claridad",
    retry: "Reintentar",
    support: "Soporte y privacidad",
    supportHint: "Canales para preguntas y solicitudes",
    terms: "Términos de uso",
    termsHint: "Condiciones del servicio y responsabilidades",
    title: "Legal y privacidad",
  },
  en: {
    eyebrow: "LEGAL CENTER",
    accept: "I confirm that I am 18 or older and accept the Privacy Notice, Terms of Use, and Community Guidelines.",
    acceptAction: "Accept and continue",
    accountDeletion: "Delete an account",
    accountDeletionHint: "Web request and process details",
    checkError: "We could not verify your acceptance. Check your connection and try again.",
    guidelines: "Community Guidelines",
    guidelinesHint: "Conduct, reports, and moderation",
    intro: "Review the current rules and how we protect your data.",
    privacy: "Privacy Notice",
    privacyHint: "Local data, cloud data, and your rights",
    reconsentBody: "We updated Community's legal foundation. Review and accept the current version to continue.",
    reconsentTitle: "We care for this space with clarity",
    retry: "Try again",
    support: "Support and privacy",
    supportHint: "Channels for questions and requests",
    terms: "Terms of Use",
    termsHint: "Service conditions and responsibilities",
    title: "Legal and privacy",
  },
  fr: {
    eyebrow: "CENTRE JURIDIQUE",
    accept: "Je confirme avoir 18 ans ou plus et j'accepte l'Avis de confidentialité, les Conditions d'utilisation et les Règles de communauté.",
    acceptAction: "Accepter et continuer",
    accountDeletion: "Supprimer un compte",
    accountDeletionHint: "Demande web et explication du processus",
    checkError: "Impossible de vérifier votre acceptation. Vérifiez la connexion et réessayez.",
    guidelines: "Règles de communauté",
    guidelinesHint: "Conduite, signalements et modération",
    intro: "Consultez les règles en vigueur et la manière dont nous protégeons vos données.",
    privacy: "Avis de confidentialité",
    privacyHint: "Données locales, données cloud et vos droits",
    reconsentBody: "Nous avons actualisé la base juridique de Communauté. Consultez et acceptez la version en vigueur.",
    reconsentTitle: "Nous protégeons cet espace avec clarté",
    retry: "Réessayer",
    support: "Assistance et confidentialité",
    supportHint: "Canaux pour questions et demandes",
    terms: "Conditions d'utilisation",
    termsHint: "Conditions du service et responsabilités",
    title: "Juridique et confidentialité",
  },
  pt: {
    eyebrow: "CENTRO JURÍDICO",
    accept: "Confirmo que tenho 18 anos ou mais e aceito o Aviso de Privacidade, os Termos de Uso e as Regras da Comunidade.",
    acceptAction: "Aceitar e continuar",
    accountDeletion: "Excluir uma conta",
    accountDeletionHint: "Solicitação web e explicação do processo",
    checkError: "Não foi possível verificar sua aceitação. Confira a conexão e tente novamente.",
    guidelines: "Regras da Comunidade",
    guidelinesHint: "Convivência, denúncias e moderação",
    intro: "Consulte as regras vigentes e como protegemos seus dados.",
    privacy: "Aviso de Privacidade",
    privacyHint: "Dados locais, dados na nuvem e seus direitos",
    reconsentBody: "Atualizamos a base jurídica da Comunidade. Revise e aceite a versão vigente para continuar.",
    reconsentTitle: "Cuidamos deste espaço com clareza",
    retry: "Tentar novamente",
    support: "Suporte e privacidade",
    supportHint: "Canais para dúvidas e solicitações",
    terms: "Termos de Uso",
    termsHint: "Condições do serviço e responsabilidades",
    title: "Legal e privacidade",
  },
} as const;

export function getLegalAccessText(language: SupportedLanguage) {
  return copy[language] ?? copy.es;
}
